'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shell=$('#shell'), cardsEl=$('#cards'), panel=$('#panel'), rail=$('#rail'), overlay=$('#overlay'), overlayList=$('#overlayList');
const C={void:'#050606',bone:'#e9e4d8',ash:'#8c8c86',amber:'#e9a81a',red:'#ba3d32',blue:'#668fa3'};
const worlds=[
{id:'engine',title:'THE MERIDIAN ENGINE',display:'THE MERIDIAN<br>ENGINE',code:'NWX-MER-01',tag:'FLAGSHIP WORLD',state:'SESSION AVAILABLE',progress:'APERTURE · 12% COMPLETE',players:'1 TRAVELER',art:'art-engine',desc:'A colossal solar machine turns beneath a silent city.',key:true},
{id:'moth',title:'MOTHWELL: BELOW',display:'MOTHWELL:<br>BELOW',code:'NWX-MWB-01',tag:'EXPLORATION WORLD',state:'WORLD READY',progress:'THE LOWER SHAFT · 8% COMPLETE',players:'1 TRAVELER',art:'art-moth',desc:'Descend into the buried city surrounding the first well.',key:false},
{id:'falcon',title:'BLACK FALCON: ASH SKY',display:'BLACK FALCON:<br>ASH SKY',code:'NWX-BFA-01',tag:'FLIGHT WORLD',state:'CHALLENGE AVAILABLE',progress:'ASH ROUTE 03 · BEST 01:42',players:'1 TRAVELER',art:'art-falcon',desc:'Cross the ash sky through towers, storms and impossible routes.',key:true},
{id:'signal',title:'DUNE SIGNAL: STATION NINE',display:'DUNE SIGNAL:<br>STATION NINE',code:'NWX-DS9-01',tag:'SIGNAL WORLD',state:'TRANSMISSION WAITING',progress:'NIGHT 04 · RELAY 71%',players:'1 TRAVELER',art:'art-signal',desc:'Investigate transmissions that have not yet been sent.',key:false},
{id:'door',title:'DOOR ZERO',display:'DOOR ZERO',code:'NWX-DZ0-01',tag:'SHARED WORLD',state:'LOCAL SESSION READY',progress:'TOWER SEED 099 · FLOOR 17',players:'1–4 TRAVELERS',art:'art-door',desc:'Build an impossible tower one changing room at a time.',key:true}
];
const spaces=[['archive','ARCHIVE','ALL OWNED WORLDS'],['sessions','SESSIONS','TRAVELERS & CONTROLLERS'],['memory','LIGHT MEMORY','SAVES, CAPTURES & HISTORY'],['observatory','OBSERVATORY','MARKS & DISCOVERIES'],['signalspace','SIGNAL','DOWNLOADS & NETWORK'],['workshop','WORKSHOP','SYSTEM SETTINGS']];
const state=JSON.parse(localStorage.getItem('highSunState')||'null')||{world:0,marks:['FIRST_LIGHT'],scores:{},touch:matchMedia('(pointer:coarse)').matches,reduced:false,contrast:false,text:1,download:36,key:null,pico:false,profile:'FAISAL'};
let selected=state.world||0, railIndex=0, overlayIndex=0, mode='horizon', audioCtx, game={active:false,type:'',t:0,score:0,data:{}}, keys={};
function save(){state.world=selected;localStorage.setItem('highSunState',JSON.stringify(state));}
function tone(freq=440,dur=.05,type='sine',vol=.025){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
const sound={move:()=>tone(520,.035,'square',.012),ok:()=>{tone(650,.06,'sine',.025);setTimeout(()=>tone(900,.08,'sine',.02),35)},back:()=>tone(260,.08,'triangle',.018),mark:()=>{tone(740,.09,'sine',.025);setTimeout(()=>tone(1110,.22,'sine',.02),70)},error:()=>tone(130,.15,'sawtooth',.02)};
function artMarkup(w){if(w.id==='engine')return '<div class="engine-rings">'+[4,12,20,28].map((n,i)=>`<i class="ring" style="--i:${n}%;--n:${i}"></i>`).join('')+'</div>';if(w.id==='moth')return '<div class="moth-well"></div><div class="moth-glow"></div>';if(w.id==='falcon')return '<div class="falcon-shape"></div>';if(w.id==='signal')return '<div class="signal-wave"></div>';return '<div class="door-grid">'+Array.from({length:28},()=>'<i></i>').join('')+'</div>'}
function renderCards(){cardsEl.innerHTML=worlds.map((w,i)=>`<article class="world-card ${i===selected?'selected':''}" data-i="${i}"><div class="world-art ${w.art}">${artMarkup(w)}</div>${w.key?'<div class="key-badge">WORLD KEY</div>':''}<div class="card-info"><div class="card-code">${w.code}</div><div class="card-title">${w.title}</div><div class="card-state">${w.state}</div></div></article>`).join('');const first=cardsEl.querySelector('.world-card');const gap=parseFloat(getComputedStyle(cardsEl).columnGap)||0;const step=(first?first.getBoundingClientRect().width:innerWidth*.53)+gap;cardsEl.style.transform=`translateX(${-selected*step}px)`;$$('.world-card').forEach(c=>c.onclick=()=>{selected=+c.dataset.i;updateWorld(true)});}
function updateWorld(playSound=false){const w=worlds[selected];if(playSound)sound.move();$('#worldCode').textContent=`${w.code} · ${w.tag}`;$('#worldTitle').innerHTML=w.display;$('#worldState').textContent=w.state;$('#worldProgress').textContent=w.progress;$('#worldPlayers').textContent=w.players;renderCards();save();}
function renderRail(){rail.innerHTML=spaces.map((s,i)=>`<button class="rail-item ${i===railIndex?'selected':''}" data-i="${i}">${s[1]}<small>${s[2]}</small></button>`).join('');$$('.rail-item').forEach(b=>b.onclick=()=>{railIndex=+b.dataset.i;openSpace(spaces[railIndex][0])})}
function toggleRail(open=true){rail.classList.toggle('open',open);mode=open?'rail':'horizon';renderRail()}
function tile(title,copy,extra=''){return `<article class="tile"><h3>${title}</h3><p>${copy}</p>${extra}</article>`}
function openSpace(id){rail.classList.remove('open');mode='panel';let title='',body='';
if(id==='archive'){title='ARCHIVE';body='<div class="grid">'+worlds.map((w,i)=>tile(w.title,`${w.code}<br>${w.desc}`,`<div class="progress"><i style="width:${[12,8,46,71,17][i]}%"></i></div>`)).join('')+'</div>'}
if(id==='sessions'){title='SESSIONS';body='<div class="grid">'+tile('FAISAL','PRIMARY TRAVELER · AXIS 01 LINKED','<div class="metric">ACTIVE</div>')+tile('GUEST SLOT','PRESS A CONTROLLER GUIDE BUTTON TO JOIN')+tile('LOCAL SESSION','DOOR ZERO · UP TO 4 TRAVELERS')+tile('VOICE','NO ACTIVE REMOTE SESSION')+'</div>'}
if(id==='memory'){title='LIGHT MEMORY';body='<div class="grid">'+tile('SECURED SAVES','5 WORLDS · LAST SYNC 2 MIN AGO','<div class="metric">24</div>')+tile('CAPTURES','7 IMAGES · 2 RECORDINGS','<div class="metric">09</div>')+tile('RAPID STATE',worlds[selected].title+' · AVAILABLE')+tile('PICO MEMORY',state.pico?'NPC-01 LINKED · RECORDS IMPORTED':'NO PICO CURRENTLY LINKED')+'</div>'}
if(id==='observatory'){title='OBSERVATORY';body='<div class="grid">'+tile('MARKS',`${state.marks.length} RECORDED`,`<div class="metric">${state.marks.length}</div>`)+tile('FIRST LIGHT','THE MACHINE REMEMBERS · PATH MARK')+tile('WORLD KEYS',`${state.key?1:0} ACTIVE · 3 REGISTERED`)+tile('PICO LEGACY','MOTHWELL · DEPTH 12 · SIGNAL 940')+'</div>'}
if(id==='signalspace'){title='SIGNAL';body='<div class="grid">'+tile('RECEIVING','MOTHWELL: BELOW — EXPANSION 01',`<div class="metric" id="downloadMetric">${state.download}%</div><div class="progress"><i id="downloadBar" style="width:${state.download}%"></i></div>`)+tile('NETWORK','WI-FI · SIGNAL STABLE · 46 MS')+tile('SYSTEM UPDATE','DAYBREAK OS MERIDIAN 0.1-DV · CURRENT')+tile('REMOTE PLAY','AVAILABLE ON LOCAL NETWORK')+'</div>'}
if(id==='workshop'){title='WORKSHOP';body='<div class="grid">'+tile('PICTURE','1440P · 120 HZ · HDR READY')+tile('SOUND','HDMI 7.1 · UI 70%')+tile('CONTROLS','AXIS 01 · HAPTICS 80%')+`<article class="tile"><h3>ACCESSIBILITY</h3><p>REDUCED MOTION · HIGH CONTRAST · TEXT SCALE</p><button onclick="HighSun.toggleSetting('reduced')">REDUCED MOTION: ${state.reduced?'ON':'OFF'}</button><br><button onclick="HighSun.toggleSetting('contrast')">HIGH CONTRAST: ${state.contrast?'ON':'OFF'}</button><br><button onclick="HighSun.textScale()">TEXT SCALE: ${state.text.toFixed(1)}×</button></article>`+tile('STORAGE','742 GB FREE · NVME READY')+tile('POWER','REST MODE · BACKGROUND UPDATES ON')+'</div>'}
panel.innerHTML=`<div class="panel-head"><div><div class="eyebrow">DAYBREAK OS MERIDIAN</div><div class="panel-title">${title}</div></div><button class="close" id="panelClose">DOOR · BACK</button></div>${body}`;panel.classList.add('open');$('#panelClose').onclick=closePanel}
function closePanel(){panel.classList.remove('open');mode='horizon';sound.back()}
function openDetails(){const w=worlds[selected];mode='panel';panel.innerHTML=`<div class="panel-head"><div><div class="eyebrow">${w.code}</div><div class="panel-title">${w.title}</div></div><button class="close" id="panelClose">DOOR · BACK</button></div><div class="grid">${tile('OVERVIEW',w.desc+'<br><br>'+w.state,'<button id="detailPlay">SUN · PLAY DEMONSTRATION</button>')}${tile('ACTIVITY',w.progress+'<br>LAST PLAYED TODAY')}${tile('MARKS',selected===0?'1 OF 12 RECORDED':'0 OF 10 RECORDED')}${tile('MEMORY','AUTOMATIC CHECKPOINT SECURED')}${tile('MANAGE',`${w.key?'WORLD KEY VERIFIED':'DIGITAL ENTITLEMENT READY'}<br>PACKAGE VERSION 0.1-DV`)}</div>`;panel.classList.add('open');$('#panelClose').onclick=closePanel;$('#detailPlay').onclick=launchGame}
function renderOverlay(){const items=['RESUME','CURRENT WORLD','CONTROLLERS','CAPTURES','AUDIO','SIMULATE WORLD KEY','CONNECT NAHAR PICO','POWER'];overlayList.innerHTML=items.map((x,i)=>`<button class="${i===overlayIndex?'selected':''}">${x}</button>`).join('');$$('#overlayList button').forEach((b,i)=>b.onclick=()=>{overlayIndex=i;overlayAction()})}
function toggleOverlay(){const open=!overlay.classList.contains('open');overlay.classList.toggle('open',open);mode=open?'overlay':(shell.classList.contains('game-open')?'game':'horizon');renderOverlay();sound[open?'ok':'back']()}
function overlayAction(){const a=overlayIndex;if(a===0)toggleOverlay();else if(a===1){toggleOverlay();openDetails()}else if(a===2)toast('CONTROLLER LINKED','AXIS 01','BATTERY 84% · HAPTICS READY');else if(a===3)toast('CAPTURE SAVED','HORIZON FRAME','LIGHT MEMORY / CAPTURES');else if(a===4)toast('AUDIO','SYSTEM VOLUME 70%','HDMI 7.1 · CONTROLLER SPEAKER ON');else if(a===5)simulateKey();else if(a===6)connectPico();else if(a===7)openPower()}
function openPower(){overlayList.innerHTML=['REST','DEEP REST','RESTART','POWER OFF','CANCEL'].map((x,i)=>`<button class="${i===0?'selected':''}">${x}</button>`).join('');$$('#overlayList button').forEach((b,i)=>b.onclick=()=>{if(i===4){toggleOverlay();return}toast('POWER STATE',b.textContent,'SIMULATION ONLY');setTimeout(()=>location.reload(),1200)})}
function simulateKey(){const w=worlds[selected];state.key=w.id;save();toast('WORLD KEY READ',w.title,w.code+' · WORLD READY');sound.mark();overlay.classList.remove('open');mode='horizon';renderCards()}
function connectPico(){state.pico=true;save();toast('NAHAR PICO FOUND','NPC-01 LINKED','LIGHT MEMORY IMPORTED · 5 PICO CARDS');sound.mark();overlay.classList.remove('open');mode='horizon'}
let toastTimer;function toast(k,t,c){clearTimeout(toastTimer);$('#toastKicker').textContent=k;$('#toastTitle').textContent=t;$('#toastCopy').textContent=c;shell.classList.add('show-toast');toastTimer=setTimeout(()=>shell.classList.remove('show-toast'),3200)}
function recordMark(id,title,copy){if(!state.marks.includes(id)){state.marks.push(id);save();sound.mark();toast('MARK RECORDED',title,copy)}}
