'use strict';
function launchGame(){panel.classList.remove('open');rail.classList.remove('open');overlay.classList.remove('open');mode='game';game={active:true,type:worlds[selected].id,t:0,score:0,data:{},last:performance.now()};shell.classList.add('game-open');$('#gameTitle').textContent=worlds[selected].title+' · WORLD DEMONSTRATION';$('#gameScore').textContent='READY';setupGame();resizeGame();game.raf=requestAnimationFrame(gameLoop);sound.ok()}
function setupGame(){const w=game.type;if(w==='engine')game.data={rings:[0,1.7,3.2],sel:0,aligned:0};if(w==='moth')game.data={x:.5,y:.72,lights:Array.from({length:7},()=>({x:.18+Math.random()*.64,y:.15+Math.random()*.68,on:true})),dark:0};if(w==='falcon')game.data={y:.5,v:0,obs:Array.from({length:7},(_,i)=>({z:i/7,x:(Math.random()-.5)*.9,gap:.18+Math.random()*.55})),distance:0};if(w==='signal')game.data={freq:4,phase:2,targetF:7,targetP:6,lock:0};if(w==='door')game.data={floor:1,doors:[0,1,2],selected:1,hp:5,light:3}}
function exitGame(){game.active=false;cancelAnimationFrame(game.raf);shell.classList.remove('game-open');mode='horizon';sound.back()}
$('#gameExit').onclick=exitGame;
const gc=$('#gameCanvas'),gctx=gc.getContext('2d');function resizeGame(){const d=devicePixelRatio||1;gc.width=innerWidth*d;gc.height=innerHeight*d;gctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resizeGame);
function gameLoop(now){if(!game.active)return;const dt=Math.min(.035,(now-game.last)/1000);game.last=now;game.t+=dt;updateGame(dt);drawGame();game.raf=requestAnimationFrame(gameLoop)}
function pressed(k){return !!keys[k]}
function updateGame(dt){const d=game.data;if(game.type==='engine'){if(pressed('ArrowLeft'))d.rings[d.sel]-=dt*1.5;if(pressed('ArrowRight'))d.rings[d.sel]+=dt*1.5;d.aligned=d.rings.filter(a=>Math.abs(Math.sin(a))<.12).length;game.score=d.aligned;$('#gameScore').textContent=`RINGS ALIGNED ${d.aligned}/3`}
if(game.type==='moth'){const s=.38*dt;if(pressed('ArrowLeft'))d.x-=s;if(pressed('ArrowRight'))d.x+=s;if(pressed('ArrowUp'))d.y-=s;if(pressed('ArrowDown'))d.y+=s;d.x=Math.max(.08,Math.min(.92,d.x));d.y=Math.max(.08,Math.min(.92,d.y));d.dark+=dt*.012;for(const l of d.lights)if(l.on&&Math.hypot(d.x-l.x,d.y-l.y)<.055){l.on=false;game.score++;tone(900,.04);if(game.score===7)recordMark('MOTH_BELOW','A LIGHT BENEATH','ALL FRAGMENTS RECOVERED')}$('#gameScore').textContent=`LIGHT ${game.score}/7`}
if(game.type==='falcon'){if(pressed('sun')||pressed('ArrowUp'))d.v-=dt*1.8;d.v+=dt*.75;d.y+=d.v*dt;d.y=Math.max(.08,Math.min(.92,d.y));d.distance+=dt*72;for(const o of d.obs){o.z-=dt*.35;if(o.z<0){o.z=1;o.x=(Math.random()-.5)*.9;o.gap=.18+Math.random()*.55;game.score++}}$('#gameScore').textContent=`DISTANCE ${Math.floor(d.distance)} · GATES ${game.score}`}
if(game.type==='signal'){if(pressed('ArrowLeft'))d.freq=Math.max(1,d.freq-dt*3);if(pressed('ArrowRight'))d.freq=Math.min(9,d.freq+dt*3);if(pressed('ArrowDown'))d.phase=Math.max(0,d.phase-dt*3);if(pressed('ArrowUp'))d.phase=Math.min(9,d.phase+dt*3);d.lock=Math.max(0,100-Math.abs(d.freq-d.targetF)*13-Math.abs(d.phase-d.targetP)*8);$('#gameScore').textContent=`LOCK ${Math.floor(d.lock)}%`;if(d.lock>96)recordMark('STATION_LOCK','MESSAGE FROM TOMORROW','STATION NINE SIGNAL RESOLVED')}
if(game.type==='door'){$('#gameScore').textContent=`FLOOR ${d.floor} · HP ${d.hp} · LIGHT ${d.light}`}}
function drawGame(){const w=innerWidth,h=innerHeight;gctx.fillStyle=C.void;gctx.fillRect(0,0,w,h);if(game.type==='engine')drawEngine(w,h);if(game.type==='moth')drawMoth(w,h);if(game.type==='falcon')drawFalcon(w,h);if(game.type==='signal')drawSignal(w,h);if(game.type==='door')drawDoor(w,h)}
function drawEngine(w,h){const d=game.data,cx=w*.5,cy=h*.52;gctx.strokeStyle='rgba(233,228,216,.35)';gctx.lineWidth=2;d.rings.forEach((a,i)=>{gctx.save();gctx.translate(cx,cy);gctx.rotate(a);gctx.beginPath();gctx.ellipse(0,0,120+i*60,55+i*32,0,0,Math.PI*2);gctx.strokeStyle=i===d.sel?C.amber:'rgba(233,228,216,.35)';gctx.stroke();gctx.fillStyle=C.amber;gctx.beginPath();gctx.arc(120+i*60,0,5,0,Math.PI*2);gctx.fill();gctx.restore()});gctx.fillStyle=C.amber;gctx.shadowColor=C.amber;gctx.shadowBlur=30;gctx.beginPath();gctx.arc(cx,cy,12+Math.sin(game.t*2)*2,0,Math.PI*2);gctx.fill();gctx.shadowBlur=0;gctx.fillStyle=C.bone;gctx.font='16px Bahnschrift';gctx.fillText('LEFT / RIGHT ROTATE · UP / DOWN SELECT RING · SUN ALIGN',28,h-44)}
function drawMoth(w,h){const d=game.data;gctx.strokeStyle='rgba(233,228,216,.12)';for(let i=0;i<14;i++){const y=(i/14*h+game.t*18)%h;gctx.beginPath();gctx.moveTo(w*.18+i%3*8,y);gctx.lineTo(w*.82-i%3*8,y+30);gctx.stroke()}for(const l of d.lights)if(l.on){gctx.fillStyle=C.amber;gctx.shadowColor=C.amber;gctx.shadowBlur=18;gctx.beginPath();gctx.arc(l.x*w,l.y*h,4,0,Math.PI*2);gctx.fill()}gctx.shadowBlur=16;gctx.fillStyle=C.bone;const x=d.x*w,y=d.y*h;gctx.beginPath();gctx.moveTo(x,y);gctx.lineTo(x-14,y-8);gctx.lineTo(x-7,y+4);gctx.lineTo(x-14,y+11);gctx.lineTo(x,y+3);gctx.lineTo(x+14,y+11);gctx.lineTo(x+7,y+4);gctx.lineTo(x+14,y-8);gctx.closePath();gctx.fill();gctx.shadowBlur=0}
function drawFalcon(w,h){const d=game.data;gctx.fillStyle='#111415';for(const o of d.obs){const scale=1/(.2+o.z);const x=w*.5+o.x*w*.4*scale;const bw=25*scale;gctx.fillRect(x-bw,h*.5-300*scale,bw*2,250*scale);gctx.fillRect(x-bw,h*.5+80*scale,bw*2,260*scale)}const x=w*.28,y=d.y*h;gctx.fillStyle=C.bone;gctx.beginPath();gctx.moveTo(x+28,y);gctx.lineTo(x-30,y-15);gctx.lineTo(x-8,y+2);gctx.lineTo(x-27,y+18);gctx.lineTo(x+4,y+7);gctx.lineTo(x+20,y+24);gctx.lineTo(x+15,y+5);gctx.closePath();gctx.fill();gctx.fillStyle=C.amber;gctx.beginPath();gctx.arc(x+4,y+5,4,0,Math.PI*2);gctx.fill()}
function drawSignal(w,h){const d=game.data;function wave(y,f,p,color){gctx.strokeStyle=color;gctx.lineWidth=2;gctx.beginPath();for(let x=0;x<w;x+=3){const yy=y+Math.sin(x*.012*f+p)*45+Math.sin(x*.032+p)*8;if(x===0)gctx.moveTo(x,yy);else gctx.lineTo(x,yy)}gctx.stroke()}wave(h*.38,d.targetF,d.targetP,C.amber);wave(h*.65,d.freq,d.phase,C.bone);gctx.fillStyle=C.ash;gctx.font='14px ui-monospace';gctx.fillText(`TARGET  F${d.targetF} P${d.targetP}`,30,h*.28);gctx.fillText(`PLAYER  F${d.freq.toFixed(1)} P${d.phase.toFixed(1)}`,30,h*.55)}
function drawDoor(w,h){const d=game.data;for(let i=0;i<3;i++){const x=w*(.25+i*.25),sel=i===d.selected;gctx.strokeStyle=sel?C.amber:'rgba(233,228,216,.35)';gctx.lineWidth=sel?4:2;gctx.strokeRect(x-70,h*.3,140,h*.45);gctx.fillStyle=sel?'rgba(233,168,26,.08)':'rgba(233,228,216,.02)';gctx.fillRect(x-70,h*.3,140,h*.45);gctx.fillStyle=sel?C.amber:C.ash;gctx.font='22px Bahnschrift';gctx.fillText(['SHADOW','LANTERN','KEY'][i],x-48,h*.55)}gctx.fillStyle=C.bone;gctx.font='15px ui-monospace';gctx.fillText('LEFT / RIGHT SELECT · SUN OPEN',30,h-45)}
