'use strict';
function act(name){if(name==='sun'){keys.sun=true;setTimeout(()=>keys.sun=false,90);if(mode==='horizon')launchGame();else if(mode==='rail')openSpace(spaces[railIndex][0]);else if(mode==='overlay')overlayAction();else if(game.type==='engine'){game.data.rings[game.data.sel]=0;sound.ok();if(game.data.rings.every(a=>Math.abs(Math.sin(a))<.12))recordMark('APERTURE_FIRST_LIGHT','FIRST LIGHT','THE MACHINE REMEMBERS')}else if(game.type==='signal'&&game.data.lock>70){game.score+=Math.floor(game.data.lock);tone(980,.12)}else if(game.type==='door'){const d=game.data;d.floor++;d.selected=Math.floor(Math.random()*3);game.score=d.floor;tone(650,.06);if(d.floor===10)recordMark('DOOR_TEN','THE TENTH LAW','TEN ROOMS SURVIVED')}}
if(name==='door'){if(mode==='panel')closePanel();else if(mode==='rail')toggleRail(false);else if(mode==='overlay')toggleOverlay();else if(mode==='game')exitGame();else openDetails()}
if(name==='signal'){if(mode==='horizon')toast('WORLD OPTIONS',worlds[selected].title,'MANAGE · KEY · MEMORY · ACCESSIBILITY')}
if(name==='mark'){if(mode==='horizon')openSpace('observatory')}
if(name==='guide')toggleOverlay();if(name==='down')toggleRail(true);if(name==='key')simulateKey()}
function nav(dir){if(mode==='horizon'){selected=(selected+(dir>0?1:-1)+worlds.length)%worlds.length;updateWorld(true)}else if(mode==='rail'){railIndex=(railIndex+(dir>0?1:-1)+spaces.length)%spaces.length;renderRail()}else if(mode==='overlay'){overlayIndex=(overlayIndex+(dir>0?1:-1)+8)%8;renderOverlay();sound.move()}else if(mode==='game'&&game.type==='engine'){game.data.sel=(game.data.sel+(dir>0?1:-1)+3)%3}else if(mode==='game'&&game.type==='door'){game.data.selected=(game.data.selected+(dir>0?1:-1)+3)%3}}
addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' ','Escape'].includes(e.key))e.preventDefault();if(e.repeat&&mode!=='game')return;if(e.key==='ArrowLeft')nav(-1);if(e.key==='ArrowRight')nav(1);if(e.key==='ArrowDown'&&mode==='horizon')toggleRail(true);if(e.key==='ArrowUp'&&mode==='rail')toggleRail(false);if(e.key==='Enter'||e.key===' '||e.key.toLowerCase()==='a')act('sun');if(e.key==='Escape'||e.key.toLowerCase()==='b')act('door');if(e.key.toLowerCase()==='x')act('signal');if(e.key.toLowerCase()==='y')act('mark');if(e.key.toLowerCase()==='q'||e.key.toLowerCase()==='g')act('guide');if(e.key.toLowerCase()==='k')act('key');if(e.key.toLowerCase()==='p')connectPico()});addEventListener('keyup',e=>keys[e.key]=false);
function pollGamepad(){const p=navigator.getGamepads?.()[0];if(p){const now=performance.now();if(!pollGamepad.last)pollGamepad.last={};const test=(id,val,fn)=>{if(val&&!pollGamepad.last[id])fn();pollGamepad.last[id]=val};test('l',p.axes[0]<-.6,()=>nav(-1));test('r',p.axes[0]>.6,()=>nav(1));test('d',p.axes[1]>.6,()=>{if(mode==='horizon')toggleRail(true)});test('a',p.buttons[0]?.pressed,()=>act('sun'));test('b',p.buttons[1]?.pressed,()=>act('door'));test('x',p.buttons[2]?.pressed,()=>act('signal'));test('y',p.buttons[3]?.pressed,()=>act('mark'));test('g',p.buttons[10]?.pressed||p.buttons[16]?.pressed,()=>act('guide'));if(mode==='game'){keys.ArrowLeft=p.axes[0]<-.2;keys.ArrowRight=p.axes[0]>.2;keys.ArrowUp=p.axes[1]<-.2;keys.ArrowDown=p.axes[1]>.2;keys.sun=p.buttons[0]?.pressed}}requestAnimationFrame(pollGamepad)}
$('#touchToggle').onclick=()=>{state.touch=!state.touch;applySettings();save()};$$('[data-btn]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();act(b.dataset.btn)});});
const stick=$('#stick'),nub=$('#nub');let stickId=null;function stickMove(e){const r=stick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),m=Math.min(46,Math.hypot(x,y)),a=Math.atan2(y,x);nub.style.transform=`translate(${Math.cos(a)*m}px,${Math.sin(a)*m}px)`;keys.ArrowLeft=x<-18;keys.ArrowRight=x>18;keys.ArrowUp=y<-18;keys.ArrowDown=y>18;if(mode!=='game'&&Math.abs(x)>45&&!stickMove.lock){nav(x>0?1:-1);stickMove.lock=true;setTimeout(()=>stickMove.lock=false,300)}}stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(stickId);stickMove(e)};stick.onpointermove=e=>{if(e.pointerId===stickId)stickMove(e)};stick.onpointerup=e=>{stickId=null;nub.style.transform='';keys.ArrowLeft=keys.ArrowRight=keys.ArrowUp=keys.ArrowDown=false};
function applySettings(){shell.classList.toggle('touch-enabled',state.touch);shell.classList.toggle('reduced',state.reduced);shell.classList.toggle('high-contrast',state.contrast);document.documentElement.style.setProperty('--textScale',state.text);$('#touchToggle').textContent=state.touch?'HIDE TOUCH':'TOUCH CONTROLS'}
window.HighSun={toggleSetting(k){state[k]=!state[k];applySettings();save();openSpace('workshop')},textScale(){state.text=state.text>=1.4?1:state.text+.2;applySettings();save();openSpace('workshop')}};
function ambient(){const c=$('#ambient'),ctx=c.getContext('2d');function rs(){const d=devicePixelRatio||1;c.width=innerWidth*d;c.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}rs();addEventListener('resize',rs);let t=0;function f(){t+=.003;const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(w*.54,h*.48,20,w*.54,h*.48,w*.65);g.addColorStop(0,'rgba(233,168,26,.08)');g.addColorStop(.35,'rgba(20,22,23,.16)');g.addColorStop(1,'rgba(0,0,0,.3)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(233,228,216,.045)';for(let i=0;i<11;i++){const y=h*.18+i*h*.07+Math.sin(t*3+i)*5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+Math.sin(t+i)*22);ctx.stroke()}requestAnimationFrame(f)}f()}
setInterval(()=>{const d=new Date();$('#clock').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(state.download<100){state.download=Math.min(100,state.download+.15);save();const m=$('#downloadMetric'),b=$('#downloadBar');if(m)m.textContent=Math.floor(state.download)+'%';if(b)b.style.width=state.download+'%'}},1000);
$('#profileName').textContent=state.profile;applySettings();renderCards();renderRail();renderOverlay();ambient();updateWorld();pollGamepad();
setTimeout(()=>{shell.classList.add('ready');$('#boot').style.opacity='0';setTimeout(()=>$('#boot').remove(),900);sound.ok();toast('CONTROLLER LINKED','AXIS 01','TRAVELER RESOLVED · HORIZON READY')},3100);

if ('serviceWorker' in navigator && location.protocol.startsWith('http')) {
  addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
}
